# Generated by Django 6.1.1 on 2026-10-04 10:19

import django.db.models.deletion
import payments.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('transaction_reference', models.CharField(default=payments.models.generate_transaction_ref, editable=False, max_length=64, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(default='SIMULATED_SANDBOX', max_length=32)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=20)),
                ('provider_status_code', models.CharField(blank=True, default='SIM_200_OK', max_length=32)),
                ('provider_message', models.TextField(blank=True, default='Simulated payment sandbox transaction.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
